blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name="main"),

    path('single_post/', views.single_post, name='single_post'),
    
    #path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('category/<slug:category_slug>/', views.post_list, name='post_list_by_category'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

details/urls.py
from django.urls import path, include
from . import views

app_name = 'details'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_us, name="about_us"),
    #path('contanct/', views.contact_us, name="contact_us"),
    path('contact/', views.feedback, name='contact_us'),
]

ikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls), # admin site
    path('accounts/', include('accounts.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('payment/', include('payment.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('coupons/', include('coupons.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('details.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [

    path('', views.product_list, name='product_list'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/<int:id>/', views.wishlist, name='add_to_wishlist'),
    path('GET/', views.product_list, name='product_list'),
    path('wishlist/remove/<int:id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<str:gender>/', views.product_list, name='product_list_by_gender'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<int:id>/<slug:slug>/<str:color>/', views.product_detail, name='product_detail_by_color'),
]

user_profile/urls.py
from django.urls import path, include
from . import views

app_name = 'user_profile'

urlpatterns = [
    path('dashboard/', views.profile_detail_view, name='profile_detail_view'),
    path('dashboard/edit/', views.edit_profile, name='edit_profile'),
]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _
#from django.core.validators import RegexValidator



class UserProfile(models.Model):

    GENDER_CHOICES = (
        ('male', _('مرد')),
        ('femal', _('زن'))
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = PhoneNumberField(_('شماره تلفن همراه'), null=True, blank=True)
    postal_code = models.IntegerField(_('کد پستی'), blank=True, null=True)
    address = models.CharField(_('آدرس'), max_length=250, null=True, blank=True)
    home_telephone = PhoneNumberField(_('شماره تلفن ثابت'), null=True, blank=True, unique=True)
    gender = models.CharField(_('جنسیت'), max_length=5, choices=GENDER_CHOICES)
    city = models.CharField(_('شهر'), max_length=100)
    photo = models.ImageField(_('عکس پروفایل'), upload_to='users/%Y/%m/%d', default='default.jpg', blank=True)

    def __str__(self):
        return f"Profile for user {self.user.username}"

    class Meta:
        verbose_name = _('پروفایل')
        verbose_name_plural = _('پروفایل ها')

user_profile/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class UserProfileForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': _('شماره تلفن همراه')}))
    postal_code = forms.CharField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': _('کد پستی')}))
    address = forms.CharField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': _('آدرس')}))
    home_telephone = forms.CharField(max_length=50, label=False, required=False, widget=forms.TextInput(attrs={'placeholder': _('شماره تلفن ثابت')}))
    city = forms.CharField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': _('شهر')}))
    gender = forms.CharField(max_length=50, label=False, required=False, widget=forms.TextInput(attrs={'placeholder': _('جنسیت')}))
    photo = forms.ImageField(label=False, required=False, widget=forms.TextInput(attrs={'placeholder': _('عکس پروفایل')}))
    class Meta:
        model = UserProfile
        fields = ('phone_number', 'postal_code', 'address', 'home_telephone', 'city', 'gender', 'photo')

class UserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': _('نام')}))
    last_name = forms.CharField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': _('نام خانوادگی')}))
    email = forms.EmailField(label=False, widget=forms.TextInput(attrs={'placeholder':_('ایمیل')}))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

user_profile/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserProfileForm, UserForm
from .models import UserProfile
from django.contrib import messages
from django.shortcuts import redirect


@login_required
def profile_detail_view(request):
    return render(request, 'user_profile/dashboard.html')

# @login_required
# def address_sidebar(request):
#     return render(request, 'user_profile/address_sidebar.html')

# @login_required
# def edit_address(request):
#     if request.method == 'POST':
#         address_form = AddressForm(request.POST or None, instance=request.user.userprofile)
#         if address_form.is_valid():
#             address_form.save()
#             return redirect('user_profile:profile_detail_view')
#     else:
#         address_form = AddressForm(instance=request.user.userprofile)
#         return render(request, 'user_profile/edit_address.html', {'address_form': address_form})
    

@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_profile = UserProfileForm(request.POST, instance=request.user.userprofile)
        user_form = UserForm(request.POST, instance=request.user)
        if user_profile.is_valid() and user_form.is_valid():
            user_profile.save()
            user_form.save()
            message = messages.success(request, 'پروفایل شما با موفقیت آپدیت شد')
            return redirect('user_profile:profile_detail_view')
        else:
            message = messages.error(request, 'لطفا تمامی فیلد ها را پر کنید')
            return redirect('user_profile:edit_profile')
    else:
        user_profile = UserProfileForm(instance=request.user.userprofile)
        user_form = UserForm(instance=request.user)
    return render(request, 'user_profile/edit_profile.html', {'user_profile': user_profile, 'user_form': user_form})

user_profile/templates/user_profile/dashboard.html
{% extends "details/base.html" %} {% load i18n static crispy_forms_tags %} {% block meta %}
<meta name="keywords" content="">
<meta name="description" content=""> {% endblock meta %} {% block title %}{% trans "داشبورد" %}{% endblock title %}
{% block content %}
<main class="main">
    <div class="page-header " style="background-image: url('/static/details/assets/images/page-header-bg.jpg')">
        <div class="container text-center">
            <h1 class="page-title">{% trans "داشبورد" %}<span>{% trans "فروشگاه" %}</span></h1>
        </div>
        <!-- End .container -->
    </div>
    <!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'details:home' %}">{% trans "خانه" %}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'shop:product_list' %}">{% trans "فروشگاه" %}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{% trans "داشبورد" %}</li>
            </ol>
        </div>
        <!-- End .container -->
    </nav>
    <!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="dashboard">
            <div class="container">
                <div class="row">

                    {% include "user_profile/sidebar.html" %}

                    <div class="col-md-8 col-lg-9">
                        <div class="tab-content">
                            <div class="tab-pane show active" id="tab-account" role="tabpanel" aria-labelledby="tab-account-link">

                                {% if messages %}
                                <ul class="success-message">
                                    {% for message in messages %}
                                    <p>
                                        <strong class="text-success">{{ message|escape }}</strong>
                                    </p>
                                    {% endfor %}
                                </ul>
                                {% endif %}

                                <div class="row">

                                    <!-- <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>نام : </strong></label> {{ user.first_name }}
                                    </div>

                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>نام خانوادگی : </strong></label> {{ user.last_name }}
                                    </div> -->

                                    <div class="content-section col-md-12 col-sm-12">
                                        <div class="media">
                                            <img src="{% if user.userprofile.image %} {{ user.userprofile.image.url }} {% else %} {% static 'img/no_image.png' %} {% endif %}" class="account-img rounded-circle">
                                        </div>
                                    </div>


                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>{% trans "نام کاربری" %} : </strong></label> {{ user.username|default:_("وارد نشده است") }}
                                        <!-- <input type="text" class="form-control" required> -->
                                    </div>

                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>{% trans "نام و نام خانوادگی" %} :‌ </strong></label> {{ user.get_full_name|default:_("وارد نشده است") }}
                                        <!-- <input type="text" class="form-control" required> -->
                                    </div>

                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>{% trans "ایمیل" %} : </strong></label> {{ user.email|default:_("وارد نشده است") }}
                                        <!-- <input type="email" class="form-control" required> -->
                                    </div>

                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>{% trans "شماره تلفن همراه" %} : </strong></label> {{ user.userprofile.phone_number|default:_("وارد نشده است") }}
                                        <!-- <input type="phone_number" class="form-control"> -->
                                    </div>

                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>{% trans "شماره تلفن ثابت" %} : </strong></label> {{ user.userprofile.home_telephone|default:_("وارد نشده است") }}
                                        <!-- <input type="phone" class="form-control"> -->
                                    </div>
                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>{% trans "کد پستی" %} : </strong></label> {{ user.userprofile.postal_code|default:_("وارد نشده است") }}
                                        <!-- <input type="city" class="form-control mb-2"> -->
                                    </div>

                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>{% trans "جنسیت" %} : </strong></label> {{ user.userprofile.gender|default:_("وارد نشده است")  }}
                                        <!-- <input type="city" class="form-control mb-2"> -->
                                    </div>

                                    <div class="form-group col-md-6 col-sm-12">
                                        <label><strong>{% trans "شهر محل سکونت" %} : </strong></label> {{ user.userprofile.city|default:_("وارد نشده است") }}
                                        <!-- <input type="city" class="form-control mb-2"> -->
                                    </div>

                                    <div class="form-group col-md-12 col-sm-12 text-right">
                                        <label class="ml-4"><strong>{% trans "آدرس" %} : </strong> {{ user.userprofile.address|default:_("وارد نشده است") }}</label>

                                        <!-- <input type="city" class="form-control mb-2"> -->
                                    </div>


                                </div>

                                <a href="{% url 'user_profile:edit_profile' %}"><button type="submit" class="btn btn-outline-primary-2 float-right">
                                        <span>{% trans "ویرایش" %}</span>
                                        <i class="icon-long-arrow-left"></i>
                                    </button></a>

                            </div>
                            <!-- .End .tab-pane -->
                        </div>
                    </div>
                    <!-- End .col-lg-9 -->
                </div>
                <!-- End .row -->
            </div>
            <!-- End .container -->
        </div>
        <!-- End .dashboard -->
    </div>
    <!-- End .page-content -->
</main>
<!-- End .main -->
{% endblock content %}

user_profile/templates/user_profile/edit_profile.html
{% extends "details/base.html" %} {% load i18n static crispy_forms_tags %} {% block meta %}
<meta name="keywords" content="">
<meta name="description" content=""> {% endblock meta %} {% block title %}{% trans "ویرایش پروفایل" %}{% endblock title %} {% block content %}
<main class="main">
    <div class="page-header text-center" style="background-image: url('/static/details/assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">{% trans "داشبورد" %}<span>{% trans "فروشگاه" %}</span></h1>
        </div>
        <!-- End .container -->
    </div>
    <!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'details:home' %}">{% trans "خانه" %}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'details:product_list' %}">{% trans "فروشگاه" %}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{% trans "داشبورد" %}</li>
            </ol>
        </div>
        <!-- End .container -->
    </nav>
    <!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="dashboard">
            <div class="container">
                <div class="row">
                    {% include "user_profile/sidebar.html" %}

                    <div class="col-md-8 col-lg-9">
                        <div class="form-tab text-right">
                            <h1 class="h4">{{ user.username }} {% trans "خوش آمدید" %}</h1>
                        </div>
                        <div class="tab-content">

                            {% if messages %}
                            <ul class="success-message">
                                {% for message in messages %}
                                <p>
                                    <strong class="text-danger">{{ message|escape }}</strong>
                                </p>
                                {% endfor %}
                            </ul>
                            {% endif %}

                            <div class="tab-pane show active" id="tab-account" role="tabpanel" aria-labelledby="tab-account-link">
                                <form action="." method="POST">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <label>{% trans "نام" %}</label> {{ user_form.first_name|as_crispy_field }}
                                        </div>
                                        <!-- End .col-sm-6 -->

                                        <div class="col-sm-6">
                                            <label>{% trans "نام خانوادگی" %}</label> {{ user_form.last_name|as_crispy_field }}
                                        </div>
                                        <!-- End .col-sm-6 -->
                                    </div>
                                    <!-- End .row -->

                                    <!-- <label>نام کاربری</label>
                                    <input type="text" class="form-control" required>
                                    <small class="form-text">این نام در قسمت بازدیدها، نظرات و حساب کاربری شما
                                        نمایش داده می شود.</small> -->

                                    <label>{% trans "ایمیل" %}</label> {{ user_form.email|as_crispy_field }}

                                    <label>{% trans "شماره تلفن همراه" %}</label> {{ user_profile.phone_number|as_crispy_field }}

                                    <label>{% trans "شماره تلفن ثابت" %}</label> {{ user_profile.home_telephone|as_crispy_field }}

                                    <label>{% trans "شهر محل سکونت" %}</label> {{ user_profile.city|as_crispy_field }}

                                    <label>{% trans "کد پستی" %}</label> {{ user_profile.postal_code|as_crispy_field }}

                                    <label>{% trans "جنسیت" %}</label> {{ user_profile.gender|as_crispy_field }}

                                    <label>{% trans "آدرس" %}</label> {{ user_profile.address|as_crispy_field }}

                                    <button type="submit" class="btn btn-outline-primary-2 float-right">
                                        <span>{% trans "ذخیره تغییرات" %}</span>
                                        <i class="icon-long-arrow-left"></i>
                                    </button>
                                </form>
                            </div>
                            <!-- .End .tab-pane -->
                        </div>
                    </div>
                    <!-- End .col-lg-9 -->
                </div>
                <!-- End .row -->
            </div>
            <!-- End .container -->
        </div>
        <!-- End .dashboard -->
    </div>
    <!-- End .page-content -->
</main>
<!-- End .main -->
{% endblock content %}

user_profile/templates/user_profile/sidebar.html
{% load i18n %}
<aside class="col-md-4 col-lg-3">
    <ul class="nav nav-dashboard flex-column mb-3 mb-md-0" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="tab-dashboard-link" href="{% url 'user_profile:profile_detail_view' %}">{% trans "داشبورد" %}</a>
        </li>
        {% comment %}          
        <li class="nav-item">
            <a class="nav-link" id="tab-orders-link" href="#tab-orders">{% trans "سفارشات" %}</a>
        </li>
        {% endcomment %}
        <li class="nav-item">
            <a class="nav-link" id="tab-downloads-link" href="{% url 'shop:wishlist' %}">{% trans "لیست علاقه مندی ها" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="tab-address-link" href="{% url 'password_change' %}">{% trans "تغییر رمز عبور" %}</a>
        </li>
        <!-- <li class="nav-item">
            <a class="nav-link" id="tab-account-link" href="">جزئیات حساب
                کاربری</a>
        </li> -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">{% trans "خروج از حساب کاربری" %}</a>
        </li>
    </ul>
</aside>