blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name="main"),

    path('single_post/', views.single_post, name='single_post'),
    
    #path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('category/<slug:category_slug>/', views.post_list, name='post_list_by_category'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

details/urls.py
from django.urls import path, include
from . import views

app_name = 'details'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_us, name="about_us"),
    #path('contanct/', views.contact_us, name="contact_us"),
    path('contact/', views.feedback, name='contact_us'),
]

ikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls), # admin site
    path('accounts/', include('accounts.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('payment/', include('payment.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('coupons/', include('coupons.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('details.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.urls import reverse
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
# from taggit.managers import TaggableManager
# from taggit.models import TagBase, GenericTaggedItemBase, TaggedItemBase
# from django.contrib.contenttypes.models import ContentType
from parler.models import TranslatableModel, TranslatedFields
from ckeditor_uploader.fields import RichTextUploadingField
# from parler.managers import TranslatableQuerySet, TranslatableManager
from django.utils.translation import gettext_lazy as _

# class CustomTag(TagBase):
#     class Meta:
#         verbose_name = "برچسب"
#         verbose_name_plural = "برچسب ها"


# class MyCustomTag(GenericTaggedItemBase, TaggedItemBase):

#     tag = models.ForeignKey(
#         CustomTag,
#         on_delete=models.CASCADE,
#         related_name="items",
#     )

class Tags(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(_('عنوان'), unique=True, max_length=50, db_index=True),
        slug = models.SlugField(unique=True, max_length=50, db_index=True)
    )

    class Meta:
        verbose_name = _("برچسب")
        verbose_name_plural = _("برچسب ها")

    def __str__(self):
        return self.name

 
class Category(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(_('عنوان'), max_length=50, db_index=True),
        slug = models.SlugField(max_length=50, db_index=True)
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("دسته بندی")
        verbose_name_plural = _("دسته بندی ها")

# class PublishedManager(models.Manager):
#     def get_queryset(self):
#         return super(PublishedManager, self).get_queryset().filter(status='منتشر شده')

class Post(TranslatableModel):

    translations = TranslatedFields(
        title = models.CharField(_('عنوان'), max_length=250),
        # slug = models.SlugField(max_length=250, unique_for_date='publish'),
        slug = models.SlugField(max_length=250),
        short_description = RichTextUploadingField(_('توضیحات مختصر'), blank=True, null=True),
        long_description = RichTextUploadingField(_('توضیحات جامع'), blank=True, null=True),
    )

    STATUS_CHOICES = (
        ('waiting', _('در انتظار')),
        ('published', _('منتشر شده')),
    )

    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name='posts', null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    publish = models.DateTimeField(_('تاریخ انتشار'), default=timezone.now)
    created = models.DateTimeField(_('تاریخ ساخت'), auto_now_add=True)
    updated = models.DateTimeField(_('تاریخ بروزرسانی'), auto_now=True)
    status = models.CharField(_('وضعیت'), max_length=10, choices=STATUS_CHOICES, default='waiting')
    # objects = models.Manager()  # The default manager
    # published = PublishedManager()  # Our custom manager
    tags = models.ManyToManyField('Tags',related_name='posts', blank=True)
    image = models.ImageField(_('تصویر'), upload_to='users/%Y/%m/%d', default='default.jpg', blank=True)

    class Meta:
        #ordering = ('-publish',)
        verbose_name = _("پست")
        verbose_name_plural = _("پست ها")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail",
                        args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class CommentManager(models.Manager):
    def all_comments(self):
        qs = super().filter(parent=None)
        return qs

class Comments(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField(_('متن پیام'), max_length=1500)
    parent = models.ForeignKey('Comments', null=True, blank=True, on_delete=models.CASCADE)
    created = models.DateTimeField(_('تاریخ ساخت'), auto_now_add=True)
    active = models.BooleanField(default=True)

    objects = CommentManager()

    class Meta:
        ordering = ['-created']
        verbose_name = _("کامنت")
        verbose_name_plural = _("کامنت ها")

    def __str__(self):
        return str(self.user.username)

    def children(self): # replies
        return Comments.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

details/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

class ContactUsMessage(models.Model):
    name = models.CharField(_('نام فرستنده'), max_length=200, help_text="Name of the sender")
    email = models.EmailField(_('ایمیل'), max_length=200)
    phone_number = PhoneNumberField(_('شماره تلفن'), null=True, blank=True)
    subject = models.CharField(_('موضوع پیام'), null=True, blank=True, max_length=200)
    body = models.TextField(_('متن پیام'))
    created_date = models.DateTimeField(_('تاریخ ایجاد'), auto_now_add=True)

    class Meta:
        verbose_name = _('تماس با ما')
        verbose_name_plural = _('تماس با ما')

    def __str__(self):
        return f"{self.name} - {self.email}"

blog/forms.py
from django import forms
from .models import Post
from .models import Comments
from django.utils.translation import gettext_lazy as _

class CommentsForm(forms.ModelForm):
    first_name = forms.CharField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': _('نام شما')}))
    # email = forms.EmailField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': _('ایمیل شما')}))
    body = forms.CharField(max_length=50, label=False, widget=forms.Textarea(attrs={'placeholder': _('دیدگاه شما')}))
    #content_type = forms.CharField(max_length=50, label=False, widget=forms.TextInput(attrs={'placeholder': 'موضوع'}))

    
    def get_comment_create_data(self, site_id=None):
        data = super(CommentsForm, self).get_comment_create_data()
        data.update({'title': self.cleaned_data['title']})
        return data

    class Meta:
        model = Comments
        fields = ('first_name', 'body',)

details/forms.py
from django import forms
from .models import ContactUsMessage
from django.forms.widgets import TextInput
from django.utils.translation import gettext_lazy as _

class ContactUsForm(forms.ModelForm):
    name = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('نام *')}))
    email = forms.EmailField(label=False, widget=forms.TextInput(attrs={'placeholder': _('ایمیل *')}))
    phone_number = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('شماره تلفن همراه')}))
    subject = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('موضوع پیام')}))
    body = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('متن پیام شما *')}))

    class Meta:
        model = ContactUsMessage
        fields = ('name', 'email', 'phone_number', 'subject', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comments, Category
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from . import forms
from django.core.mail import send_mail
from .models import Tags
from django.contrib.auth.models import User
from user_profile.models import UserProfile


# def blog(request):
#     posts = Post.objects.all()
#     return render(request, 'blog/detail.html', {'posts': posts})

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'

def get_all_categories():
    return Category.objects.all()

def get_three_latest_posts():
    return Post.objects.filter(status='published')[0:3]

def get_all_tags():
    return Tags.objects.all()

def single_post(request):
    return render(request, 'blog/detail.html')

def post_list(request, tag_slug=None, category_slug=None):
    language = request.LANGUAGE_CODE
    object_list = Post.objects.all()
    latest_posts = object_list[:3]

    # username = None
    # if user_name:
    #     username = get_object_or_404(User, slug=user_name)
    #     object_list = object_list.filter(user=request.user)

    category = None
    if category_slug:
        category = get_object_or_404(Category, translations__slug=category_slug, translations__language_code=language)
        object_list = object_list.filter(category__in=[category])

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tags, translations__slug=tag_slug, translations__language_code=language)
        object_list = object_list.filter(tags__in=[tag])

    page = request.GET.get('page', 1)
    paginator = Paginator(object_list, 4) # 4 posts in each page
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    context =  {'posts': posts, 'tag': tag, 'category': category, 'three_latest_posts': latest_posts,
                'tags': get_all_tags(), 'categories': get_all_categories()}
                
    return render(request, 'blog/list.html', context=context)

def post_detail(request, year, month, day, post):
    language = request.LANGUAGE_CODE
    print(language)
    posts = Post.objects.filter(status='published')[:10]   # Related posts in detail page
    post = get_object_or_404(Post, translations__slug=post, status='published',
                               publish__year=year, publish__month=month,
                               publish__day=day, translations__language_code=language)

    # The code below is for getting next and previous object
    # and if object does not exists, we set it to None.
    try:
        next_post_id = post.id + 1
        next_post = get_object_or_404(Post ,id=next_post_id)
    except:
        next_post = None
    try:
        previouse_post_id = post.id - 1
        previous_post = get_object_or_404(Post ,id=previouse_post_id)
    except:
        previous_post = None

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    
    new_comment = None

    if request.method == 'POST': 
        comment_form = forms.CommentsForm(request.POST)
        if comment_form.is_valid():
            # Create comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.user = request.user
            new_comment.save()
    else:
        comment_form = forms.CommentsForm()

    context = {'post': post, 'comments': comments, 'new_comment': new_comment,
                'comment_form': comment_form, 'three_latest_posts': get_three_latest_posts(),
                'tags': get_all_tags(), 'categories': get_all_categories(),
                'next_post': next_post, 'previous_post': previous_post, 'posts': posts,
                'share_telegram': {'url': post.get_absolute_url, 'text': post.title, 'link_text': "<i title='Telegram' class='fa fa-telegram mr-3' style='font-size:24px;color:#2196F3;'></i>" },
                'share_whatsapp': {'url': post.get_absolute_url, 'text': "<i title='Whatsapp' class='fab fa fa-whatsapp mr-3' style='font-size:24px;color:#1bd741;'></i>" },
                'share_linkedin': {'url': post.get_absolute_url},
                }

    return render(request, 'blog/detail.html', context=context)

    

details/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from . import forms
from shop.models import Product
from django.contrib.auth.models import User


def home(request):
    latest_products = Product.objects.all()[:10]
    context = {'products': latest_products}
    return render(request, 'details/home.html', context=context)

def about_us(request):
    user = User.objects.all()
    context = {'user': user}
    return render(request, 'details/about.html', context=context)

def feedback(request):
    if request.method == 'POST':
        feedback = forms.ContactUsForm(request.POST)
        if feedback.is_valid():
            feedback.save()
            messages.add_message(request, messages.INFO, 'ممنون از اینکه نظرات خود را با ما در میان میگذارید.')
            return redirect('details:contact_us')
    else:
        feedback = forms.ContactUsForm()
    return render(request, 'details/contact.html', {'feedback': feedback})

blog/templates/blog/aside.html
{% load i18n static %}

<aside class="col-lg-3">
    <div class="sidebar">
        <div class="widget widget-search">
            <h3 class="widget-title">{% trans "جستجو" %}</h3>
            <!-- End .widget-title -->

            <form action="#">
                <label for="ws" class="sr-only">{% trans "جستجوی اخبار" %}</label>
                <input type="search" class="form-control" name="ws" id="ws" placeholder="{% trans 'جستجوی خبر مورد نظر' %}" required>
                <button type="submit" class="btn"><i class="icon-search"></i><span
                                class="sr-only">{% trans "جستجو" %}</span></button>
            </form>
        </div>
        <!-- End .widget -->

        <div class="widget widget-cats">
            <h3 class="widget-title">{% trans "دسته بندی ها" %}</h3>
            <!-- End .widget-title -->

            <ul>
                {% for category in categories %} <a href="{% url 'blog:post_list_by_category' category.slug %}"> {{ category.name }} <span>{{ category.posts.count }}</span> </a> {% if not forloop.last %} {% endif %} {% endfor %}
            </ul>
        </div>
        <!-- End .widget -->

        <div class="widget">
            <h3 class="widget-title">{% trans "پست های اخیر" %}</h3>
            <!-- End .widget-title -->

            <ul class="posts-list">
                {% for post in three_latest_posts %}
                <li>
                    <figure>
                        <a href="#">
                            <img src="{{ post.image.url }}" alt="post">
                        </a>
                    </figure>

                    <div>
                        <span>{{ post.publish }}</span>
                        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                    </div>
                </li>
                {% endfor %}
                <!-- <li>
                    <figure>
                        <a href="#">
                            <img src="{% static 'details/assets/images/blog/sidebar/post-2.jpg' %}" alt="post">
                        </a>
                    </figure>

                    <div>
                        <span>19 فروردین 1399</span>
                        <h4><a href="#">لورم ایپسوم متن ساختگی</a></h4>
                    </div>
                </li>
                <li>
                    <figure>
                        <a href="#">
                            <img src="{% static 'details/assets/images/blog/sidebar/post-3.jpg' %}" alt="post">
                        </a>
                    </figure>

                    <div>
                        <span>12 فروردین 1399</span>
                        <h4><a href="#">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</a></h4>
                    </div>
                </li>
                <li>
                    <figure>
                        <a href="#">
                            <img src="{% static 'details/assets/images/blog/sidebar/post-4.jpg' %}" alt="post">
                        </a>
                    </figure>

                    <div>
                        <span>25 فروردین 1399</span>
                        <h4><a href="#">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</a></h4>
                    </div>
                </li> -->
            </ul>
            <!-- End .posts-list -->
        </div>
        <!-- End .widget -->

        <!-- <div class="widget widget-banner-sidebar">
            <div class="banner-sidebar-title">قسمت تبلیغات 280 در 280</div>

            <div class="banner-sidebar banner-overlay">
                <a href="#">
                    <img src="{% static 'details/assets/images/blog/sidebar/banner.jpg' %}" alt="بنر">
                </a>
            </div>
        </div> -->

        <div class="widget">
            <h3 class="widget-title">{% trans "برچسب ها" %}</h3>

            <div class="tagcloud">
                {% for tag in tags %} <a href="{% url 'blog:post_list_by_tag' tag.slug %}"> {{ tag.name }} </a> {% if not forloop.last %} {% endif %} {% endfor %}
            </div>
        </div>

        <!-- <div class="widget widget-text">
            <h3 class="widget-title">درباره بخش اخبار</h3>

            <div class="widget-text-content">
                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
            </div>
        </div> -->
        <!-- End .widget -->
    </div>
    <!-- End .sidebar -->
</aside>
<!-- End .col-lg-3 -->

blog/templates/blog/list.html
{% extends 'details/base.html' %} {% load i18n static l10n %} {% block meta %}
<meta name="keywords" content="">
<meta name="description" content=""> {% endblock meta %} {% block title %}وبلاگ{% endblock title %} {% block head %}
<link rel="stylesheet" href="/static/details/assets/css/plugins/owl-carousel/owl.carousel.css">{% endblock head %} {% block content %}

<main class="main">
    <div class="page-header text-center" style="background-image: url('/static/details/assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">{% trans "وبلاگ" %}<span>{% trans "اخبار" %}</span></h1>
        </div>
        <!-- End .container -->
    </div>
    <!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">{% trans "خانه" %}</a></li>
                <li class="breadcrumb-item"><a href="#">{% trans "اخبار" %}</a></li>
            </ol>
        </div>
        <!-- End .container -->
    </nav>
    <!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    {% if tag %}
                    <h2 class="h4 text-right">{% trans "فیلتر بر اساس" %}: "{{ tag.name }}"</h2>
                    {% endif %} {% for post in posts %}
                    <article class="entry">
                        <figure class="entry-media">
                            <a href="{{ post.get_absolute_url }}">
                                <img src="{{ post.image.url }}" alt="توضیحات عکس">
                            </a>
                        </figure>
                        <!-- End .entry-media -->

                        <div class="entry-body">
                            <div class="entry-meta">
                                <span class="entry-author">
                                            <a href="#">{{ user.username }}</a>
                                </span>
                                <span class="meta-separator">|</span>
                                <a href="#">{{ post.publish|localize }}</a>
                                <!-- <span class="meta-separator">|</span>
                                <a href="#">2 دیدگاه</a> -->
                            </div>
                            <!-- End .entry-meta -->

                            <h2 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h2>
                            <!-- End .entry-title -->

                            <div class="entry-cats">
                                {% for tag in post.tags.all %} <a href="{% url 'blog:post_list_by_tag' tag.slug %}"> {{ tag.name }} </a> {% if not forloop.last %}, {% endif %}{% endfor %}
                            </div>
                            <!-- End .entry-cats -->

                            <div class="entry-content">
                                <p>{{ post.short_description|safe|truncatewords:30|linebreaks }}</p>
                                <a href="{{ post.get_absolute_url }}" class="read-more">{% trans "ادامه خواندن" %}</a>
                            </div>
                            <!-- End .entry-content -->
                        </div>
                        <!-- End .entry-body -->
                    </article>
                    <!-- End .entry -->
                    {% endfor %} {% comment %}
                    <!-- <nav aria-label="Page navigation">
                        <ul class="pagination">

                            {% if posts.has_other_pages %} {% if posts.has_previous %}

                            <li class="page-item">
                                <a class="page-link page-link-prev" href="?page={{ posts.previous_page_number }}" aria-label="Previous" tabindex="-1" aria-disabled="true">
                                    <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>قبلی
                                </a>
                            </li>


                            {% endif %}
                            <li class="page-item" aria-current="page">
                                <a class="page-link" href="?page=1">1</a>
                            </li>
                            {% if posts.number != 1 %}
                                <li class="page-item" aria-current="page">
                                <a class="page-link" href="#">...</a>
                            </li>
                            {% endif %}
                            {% for i in posts.paginator.page_range %} {% if posts.number == i and i != posts.paginator.num_pages and i != 1 %}

                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="#">{{ i }}</a>
                            </li>

                          
                            {% elif i <= posts.number|add:1 and i >= posts.number|add:-1 and i != posts.paginator.num_pages and i != 1 %}
                                <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                           
                            {% endif %} {% endfor %}
                            {% if posts.number != posts.paginator.num_pages %}
                                <li class="page-item" aria-current="page">
                                <a class="page-link" href="#">...</a>
                            </li>
                            {% endif %}
                            <li class="page-item" aria-current="page">
                                <a class="page-link" href="?page={{ posts.paginator.num_pages }}">{{ posts.paginator.num_pages }}</a>
                            </li>
                            {% if posts.has_next %}

                            <li class="page-item">
                                <a class="page-link page-link-next" href="?page={{ posts.next_page_number }}" aria-label="Next">
                                            بعدی <span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>
                                </a>
                            </li>
                            {% endif %} {% endif %}
                        </ul>
                    </nav> -->
                    {% endcomment %}

                    <!-- Pagination -->
                    {% include "blog/pagination.html" %}

                </div>

                <!-- This part is for aside tag -->
                {% include "blog/aside.html" %}

            </div>
            <!-- End .row -->
        </div>
        <!-- End .container -->
    </div>
    <!-- End .page-content -->
</main>
<!-- End .ma-->
{% endblock content %}

blog/templates/blog/pagination.html
{% load i18n %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if posts.has_other_pages %} {% with posts.number|stringformat:"i" as pgnumber %} {% with myfilter='page='|add:pgnumber|add:'&' request_query=request.META.QUERY_STRING %} {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link page-link-prev" href="?page={{ posts.previous_page_number }}&{{ request_query|cut:myfilter }}" aria-label="Previous" tabindex="-1" aria-disabled="true">
                <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>{% trans "قبلی" %}
            </a>
        </li>
        {% endif %} {% if posts.number != 1 %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="?page=1&{{ request_query|cut:myfilter }}">1</a>
        </li>
        {% endif %} {% if posts.number != 1 and posts.number != 2 and posts.number != 3 %}
        <li class="page-item" aria-current="page">
            ...
        </li>
        {% endif %} {% if posts.has_previous and posts.number != 2 %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="?page={{ posts.number|add:-1 }}&{{ request_query|cut:myfilter }}">{{ posts.number|add:-1 }}</a>
        </li>
        {% endif %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ posts.number}}</a>
        </li>
        {% if posts.has_next and posts.number != posts.paginator.num_pages|add:-1 %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="?page={{ posts.number|add:1 }}&{{ request_query|cut:myfilter }}">{{ posts.number|add:1 }}</a>
        </li>
        {% endif %} {% if posts.number != posts.paginator.num_pages and posts.number != posts.paginator.num_pages|add:-1 and posts.number != posts.paginator.num_pages|add:-2 %}
        <li class="page-item" aria-current="page">
            ...
        </li>
        {% endif %} {% if posts.number != posts.paginator.num_pages %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="?page={{ posts.paginator.num_pages }}&{{ request_query|cut:myfilter }}">{{ posts.paginator.num_pages }}</a>
        </li>
        {% endif %} {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link page-link-next" href="?page={{ posts.next_page_number }}&{{ request_query|cut:myfilter }}" aria-label="Next">
                         {% trans "بعدی" %}<span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>
            </a>
        </li>
        {% endif %} {% endwith %} {% endwith %} {% endif %}
    </ul>
</nav>