blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name="main"),

    path('single_post/', views.single_post, name='single_post'),
    
    #path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('category/<slug:category_slug>/', views.post_list, name='post_list_by_category'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

details/urls.py
from django.urls import path, include
from . import views

app_name = 'details'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_us, name="about_us"),
    #path('contanct/', views.contact_us, name="contact_us"),
    path('contact/', views.feedback, name='contact_us'),
]

ikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls), # admin site
    path('accounts/', include('accounts.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('payment/', include('payment.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('coupons/', include('coupons.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('details.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

details/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

class ContactUsMessage(models.Model):
    name = models.CharField(_('نام فرستنده'), max_length=200, help_text="Name of the sender")
    email = models.EmailField(_('ایمیل'), max_length=200)
    phone_number = PhoneNumberField(_('شماره تلفن'), null=True, blank=True)
    subject = models.CharField(_('موضوع پیام'), null=True, blank=True, max_length=200)
    body = models.TextField(_('متن پیام'))
    created_date = models.DateTimeField(_('تاریخ ایجاد'), auto_now_add=True)

    class Meta:
        verbose_name = _('تماس با ما')
        verbose_name_plural = _('تماس با ما')

    def __str__(self):
        return f"{self.name} - {self.email}"

details/forms.py
from django import forms
from .models import ContactUsMessage
from django.forms.widgets import TextInput
from django.utils.translation import gettext_lazy as _

class ContactUsForm(forms.ModelForm):
    name = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('نام *')}))
    email = forms.EmailField(label=False, widget=forms.TextInput(attrs={'placeholder': _('ایمیل *')}))
    phone_number = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('شماره تلفن همراه')}))
    subject = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('موضوع پیام')}))
    body = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('متن پیام شما *')}))

    class Meta:
        model = ContactUsMessage
        fields = ('name', 'email', 'phone_number', 'subject', 'body')

details/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from . import forms
from shop.models import Product
from django.contrib.auth.models import User


def home(request):
    latest_products = Product.objects.all()[:10]
    context = {'products': latest_products}
    return render(request, 'details/home.html', context=context)

def about_us(request):
    user = User.objects.all()
    context = {'user': user}
    return render(request, 'details/about.html', context=context)

def feedback(request):
    if request.method == 'POST':
        feedback = forms.ContactUsForm(request.POST)
        if feedback.is_valid():
            feedback.save()
            messages.add_message(request, messages.INFO, 'ممنون از اینکه نظرات خود را با ما در میان میگذارید.')
            return redirect('details:contact_us')
    else:
        feedback = forms.ContactUsForm()
    return render(request, 'details/contact.html', {'feedback': feedback})

details/templates/details/about.html
{% extends 'details/base.html' %} {% load i18n static crispy_forms_tags %} {% block meta %}
<meta name="keywords" content="">
<meta name="description" content=""> {% endblock meta %} {% block title %} درباره ما{% endblock title %} {% block head %}
<link rel="stylesheet" href="{% static 'details/assets/css/plugins/owl-carousel/owl.carousel.css' %}"> {% endblock head %} {% block content %}
<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">{% trans "خانه" %}</a></li>
                <li class="breadcrumb-item"><a href="#">{% trans "صفحات" %}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{% trans "درباره ما" %}</li>
            </ol>
        </div>
        <!-- End .container -->
    </nav>
    <!-- End .breadcrumb-nav -->
    <div class="container">
        <div class="page-header page-header-big text-center" style="background-image: url('/static/details/assets/images/about-header-bg.jpg')">
            <h1 class="page-title text-white">{% trans "درباره ما" %}<span class="text-white">{% trans "درباره فروشگاه ما" %}</span></h1>
        </div>
        <!-- End .page-header -->
    </div>
    <!-- End .container -->

    <div class="page-content pb-0">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-3 mb-lg-0">
                    <h2 class="title">{% trans "دید ما" %}</h2>
                    <!-- End .title -->
                    <p>{% trans "ما اینجا گرد هم آمده ایم تا یه حرکتی بزنیم" %}. </p>
                </div>
                <!-- End .col-lg-6 -->

                <div class="col-lg-6">
                    <h2 class="title">{% trans "ماموریت ما" %}</h2>
                    <!-- End .title -->
                    <p>{% trans "همون حرکتی که قرار بود بزنیم!" %} </p>
                </div>
                <!-- End .col-lg-6 -->
            </div>
            <!-- End .row -->

            <div class="mb-5"></div>
            <!-- End .mb-4 -->
        </div>
        <!-- End .container -->

        <div class="bg-light-2 pt-6 pb-5 mb-6 mb-lg-8">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 mb-3 mb-lg-0">
                        <h2 class="title">{% trans "ما که هستیم" %}</h2>
                        <!-- End .title -->
                        <p class="lead text-primary mb-3">{% trans "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم" %}<br>{% trans "لورم ایپسوم متن ساختگی با تولید سادگی" %}</p>
                        <!-- End .lead text-primary -->
                        <p class="mb-2">{% trans "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم" %}. </p>

                        <a href="{% url 'blog:main' %}" class="btn btn-sm btn-minwidth btn-outline-primary-2 float-right">
                            <span>{% trans "مشاهده دیگر خبرها" %}</span>
                            <i class="icon-long-arrow-left"></i>
                        </a>
                    </div>
                    <!-- End .col-lg-5 -->

                    <div class="col-lg-6 offset-lg-1">
                        <div class="about-images">
                            <img src="{% static 'details/assets/images/about/img-1.jpg' %}" alt="" class="about-img-front">
                            <img src="{% static 'details/assets/images/about/img-2.jpg' %}" alt="" class="about-img-back">
                        </div>
                        <!-- End .about-images -->
                    </div>
                    <!-- End .col-lg-6 -->
                </div>
                <!-- End .row -->
            </div>
            <!-- End .container -->
        </div>
        <!-- End .bg-light-2 pt-6 pb-6 -->

        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <div class="brands-text">
                        <h2 class="title">{% trans "برند های معروفی که با ما در حال همکاری هستند" %}.</h2>
                        <!-- End .title -->
                        <p>{% trans "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم" %}</p>
                    </div>
                    <!-- End .brands-text -->
                </div>
                <!-- End .col-lg-5 -->
                <div class="col-lg-7">
                    <div class="brands-display">
                        <div class="row justify-content-center">
                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/1.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->

                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/2.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->

                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/3.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->

                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/4.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->

                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/5.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->

                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/6.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->

                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/7.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->

                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/8.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->

                            <div class="col-6 col-sm-4">
                                <a href="#" class="brand">
                                    <img src="{% static 'details/assets/images/brands/9.png' %}" alt="نام برند">
                                </a>
                            </div>
                            <!-- End .col-sm-4 -->
                        </div>
                        <!-- End .row -->
                    </div>
                    <!-- End .brands-display -->
                </div>
                <!-- End .col-lg-7 -->
            </div>
            <!-- End .row -->

            <hr class="mt-4 mb-6">

            <h2 class="title text-center mb-4">{% trans "آشنایی با تیم ما" %}</h2>
            <!-- End .title text-center mb-2 -->

            <div class="row">
                {% for user in users %} {% if user.is_superuser %}
                <div class="col-md-4">
                    <div class="member member-anim text-center">
                        <figure class="member-media">
                            <img src="{% static 'details/assets/images/team/member-1.jpg' %}" alt="توضیح عکس">

                            <figcaption class="member-overlay">
                                <div class="member-overlay-content">
                                    <h3 class="member-title">نرگس رسولی<span>جستجو و سئو</span></h3>
                                    <!-- End .member-title -->
                                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</p>
                                    <div class="social-icons social-icons-simple">
                                        <a href="#" class="social-icon" title="فیسبوک" target="_blank"><i
                                                        class="icon-facebook-f"></i></a>
                                        <a href="#" class="social-icon" title="توییتر" target="_blank"><i
                                                        class="icon-twitter"></i></a>
                                        <a href="#" class="social-icon" title="اینستاگرام" target="_blank"><i
                                                        class="icon-instagram"></i></a>
                                    </div>
                                    <!-- End .soial-icons -->
                                </div>
                                <!-- End .member-overlay-content -->
                            </figcaption>
                            <!-- End .member-overlay -->
                        </figure>
                        <!-- End .member-media -->
                        <div class="member-content">
                            <h3 class="member-title">نرگس رسولی<span>جستجو و سئو</span></h3>
                            <!-- End .member-title -->
                        </div>
                        <!-- End .member-content -->
                    </div>
                    <!-- End .member -->
                </div> {% endif %} {% endfor %}
                <!-- End .col-md-4 -->
            </div>
            <!-- End .row -->
        </div>
        <!-- End .container -->

        <div class="mb-2"></div>
        <!-- End .mb-2 -->

        <div class="about-testimonials bg-light-2 pt-6 pb-6">
            <div class="container">
                <h2 class="title text-center mb-3">{% trans "نظرات مشتری های فروشگاه" %}</h2>
                <!-- End .title text-center -->

                <div class="owl-carousel owl-simple owl-testimonials-photo" data-toggle="owl" data-owl-options='{
                                "nav": false, 
                                "dots": true,
                                "margin": 20,
                                "loop": false,
                                "responsive": {
                                    "1200": {
                                        "nav": true
                                    }
                                }
                            }'>
                    {% for comment in user.comments %}
                    <blockquote class="testimonial text-center">
                        <img src="{% static 'details/assets/images/testimonials/user-1.jpg' %}" alt="user">
                        <p>“ {% trans "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم" %} ”</p>
                        <cite>
                                    مشتری 1
                                    <span>{% trans "مشتری" %}</span>
                                </cite>
                    </blockquote> {% endfor %}
                    <!-- End .testimonial -->
                </div>
                <!-- End .testimonials-slider owl-carousel -->
            </div>
            <!-- End .container -->
        </div>
        <!-- End .bg-light-2 pt-5 pb-6 -->
    </div>
    <!-- End .page-content -->
</main>
<!-- End .main -->
{% endblock content %}

details/templates/details/contact.html
{% extends 'details/base.html' %} {% load i18n static crispy_forms_tags %} {% block meta %}
<meta name="keywords" content="">
<meta name="description" content=""> {% endblock meta %} {% block title %} {% trans "تماس با ما" %} {% endblock title %} {% block content %}
<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">{% trans "خانه" %}</a></li>
                <li class="breadcrumb-item"><a href="#">{% trans "صفحات" %}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{% trans "تماس با ما" %}</li>
            </ol>
        </div>
        <!-- End .container -->
    </nav>
    <!-- End .breadcrumb-nav -->
    <div class="container">
        <div class="page-header page-header-big text-center" style="background-image: url('/static/details/assets/images/contact-header-bg.jpg')">
            <h1 class="page-title text-white">{% trans "تماس با ما" %}<span class="text-white">{% trans "ارتباط خود را با ما حفظ کنید" %}</span></h1>
        </div>
        <!-- End .page-header -->
    </div>
    <!-- End .container -->

    <div class="page-content pb-0">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-2 mb-lg-0">
                    <h2 class="title mb-1">{% trans "اطلاعات تماس" %}</h2>
                    <!-- End .title mb-2 -->
                    <p class="mb-3">{% trans "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم" %}.</p>
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="contact-info">
                                <h3>{% trans "دفتر" %}</h3>

                                <ul class="contact-list">
                                    <li>
                                        <i class="icon-map-marker"></i>{% trans " تهران، میدان آزادی، خیابان آزادی، پلاک 7" %}
                                    </li>
                                    <li>
                                        <i class="icon-phone"></i>
                                        <a href="tel:#">55667788</a>
                                    </li>
                                    <li>
                                        <i class="icon-envelope"></i>
                                        <a href="mailto:#">info@example.com</a>
                                    </li>
                                </ul>
                                <!-- End .contact-list -->
                            </div>
                            <!-- End .contact-info -->
                        </div>
                        <!-- End .col-sm-7 -->

                        <div class="col-sm-5">
                            <div class="contact-info">
                                <h3>{% trans "ساعت کار دفتر" %}</h3>

                                <ul class="contact-list">
                                    <li>
                                        <i class="icon-clock-o"></i>
                                        <span class="text-dark">{% trans "شنبه تا چهارشنبه" %}</span> <br>{% trans "11 صبح تا 7 عصر" %}
                                    </li>
                                    <li>
                                        <i class="icon-calendar"></i>
                                        <span class="text-dark">{% trans "پنج شنبه" %}</span> <br>{% trans "11 صبح تا 5 عصر" %}
                                    </li>
                                </ul>
                                <!-- End .contact-list -->
                            </div>
                            <!-- End .contact-info -->
                        </div>
                        <!-- End .col-sm-5 -->
                    </div>
                    <!-- End .row -->
                </div>
                <!-- End .col-lg-6 -->
                <div class="col-lg-6">
                    <h2 class="title mb-1">{% trans "سوالی دارید؟" %}</h2>
                    <!-- End .title mb-2 -->
                    <p class="mb-2">{% trans "با استفاده از فرم زیر می توانید با ما ارتباط برقرار کنید" %}</p>

                    <form action="." method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-6">
                                <label for="cname" class="sr-only">{% trans "نام" %}</label> {{ feedback.name|as_crispy_field }}
                                <!-- <input type="text" class="form-control" id="cname" placeholder="نام خود را وارد کنید *" required> -->
                            </div>
                            <!-- End .col-sm-6 -->

                            <div class="col-sm-6">
                                <label for="cemail" class="sr-only">{% trans "ایمیل" %}</label> {{ feedback.email|as_crispy_field }}
                                <!-- <input type="email" class="form-control" id="cemail" placeholder="ایمیل خود را وارد کنید *" required> -->
                            </div>
                            <!-- End .col-sm-6 -->
                        </div>
                        <!-- End .row -->

                        <div class="row">
                            <div class="col-sm-6">
                                <label for="cphone" class="sr-only">{% trans "شماره موبایل" %}</label> {{ feedback.phone_number|as_crispy_field }}
                                <!-- <input type="tel" class="form-control" id="cphone" placeholder="شماره موبایل خود را وارد کنید"> -->
                            </div>
                            <!-- End .col-sm-6 -->

                            <div class="col-sm-6">
                                <label for="csubject" class="sr-only">{% trans "موضوع" %}</label> {{ feedback.subject|as_crispy_field }}
                                <!-- <input type="text" class="form-control" id="csubject" placeholder="موضوع پیام شما"> -->
                            </div>
                            <!-- End .col-sm-6 -->
                        </div>
                        <!-- End .row -->

                        <label for="cmessage" class="sr-only">{% trans "پیام" %}</label> {{ feedback.body|as_crispy_field }}
                        <!-- <textarea class="form-control" cols="30" rows="4" id="cmessage" required placeholder="متن پیام شما *"></textarea> -->

                        {% if messages %}
                        <ul class="error-message">
                            {% for message in messages %}
                            <p>
                                <strong class="text-info">{{ message|escape }}</strong>
                            </p>
                            {% endfor %}
                        </ul>
                        {% endif %}

                        <button type="submit" class="btn btn-outline-primary-2 btn-minwidth-sm float-right">
                                    <span>{% trans "تایید و ارسال" %}</span>
                                    <i class="icon-long-arrow-left"></i>
                        </button>
                    </form>
                    <!-- End .contact-form -->
                </div>
                <!-- End .col-lg-6 -->
            </div>
            <!-- End .row -->

            <hr class="mt-4 mb-5">

            <div class="stores mb-4 mb-lg-5">
                <h2 class="title text-center mb-3">{% trans "فروشگاه های ما" %}</h2>
                <!-- End .title text-center mb-2 -->

                <div class="row">
                    <div class="col-lg-6">
                        <div class="store">
                            <div class="row">
                                <div class="col-sm-5 col-xl-6">
                                    <figure class="store-media mb-2 mb-lg-0">
                                        <img src="{% static 'details/assets/images/stores/img-1.jpg' %}" alt="image">
                                    </figure>
                                    <!-- End .store-media -->
                                </div>
                                <!-- End .col-xl-6 -->
                                <div class="col-sm-7 col-xl-6">
                                    <div class="store-content">
                                        <h3 class="store-title">{% trans "فروشگاه شماره 1" %}</h3>
                                        <!-- End .store-title -->
                                        <address>{% trans "تهران، میدان تجریش" %}</address>
                                        <div><a href="tel:#">88776655</a></div>

                                        <h4 class="store-subtitle">{% trans "ساعت کاری فروشگاه" %} :</h4>
                                        <!-- End .store-subtitle -->
                                        <div>{% trans "شنبه-چهارشنبه 11صبح تا 7 عصر" %}</div>
                                        <div>{% trans "پنج شنبه 11 صبح تا 6 عصر" %}</div>

                                        <a href="#" class="btn btn-link" target="_blank"><span>{% trans "مشاهده روی نقشه" %}</span><i class="icon-long-arrow-left"></i></a>
                                    </div>
                                    <!-- End .store-content -->
                                </div>
                                <!-- End .col-xl-6 -->
                            </div>
                            <!-- End .row -->
                        </div>
                        <!-- End .store -->
                    </div>
                    <!-- End .col-lg-6 -->

                    {% comment %}
                    <div class="col-lg-6">
                        <div class="store">
                            <div class="row">
                                <div class="col-sm-5 col-xl-6">
                                    <figure class="store-media mb-2 mb-lg-0">
                                        <img src="{% static  'details/assets/images/stores/img-2.jpg' %}" alt="image">
                                    </figure>
                                    <!-- End .store-media -->
                                </div>
                                <!-- End .col-xl-6 -->

                                <div class="col-sm-7 col-xl-6">
                                    <div class="store-content">
                                        <h3 class="store-title">فروشگاه شماره 2</h3>
                                        <!-- End .store-title -->
                                        <address>تهران، میدان منیریه</address>
                                        <div><a href="tel:#">77558866</a></div>

                                        <h4 class="store-subtitle">ساعت کاری فروشگاه :</h4>
                                        <!-- End .store-subtitle -->
                                        <div>شنبه-چهارشنبه 11صبح تا 7 عصر</div>
                                        <div>پنج شنبه 11 صبح تا 6 عصر</div>
                                        <div>جمعه - تعطیل</div>

                                        <a href="#" class="btn btn-link" target="_blank"><span>مشاهده روی
                                                        نقشه</span><i class="icon-long-arrow-left"></i></a>
                                    </div>
                                    <!-- End .store-content -->
                                </div>
                                <!-- End .col-xl-6 -->

                            </div>
                            <!-- End .row -->
                        </div>
                        <!-- End .store -->
                    </div>{% endcomment %}
                    <!-- End .col-lg-6 -->
                </div>
                <!-- End .row -->
            </div>
            <!-- End .stores -->
        </div>
        <!-- End .container -->
        <div class="col-12 d-flex">
            <div class="bg-white w-100">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.0762034011345!2d51.33938432078328!3d35.69974233666176!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzXCsDQxJzU5LjEiTiA1McKwMjAnMTMuOSJF!5e0!3m2!1sfa!2s!4v1585894944267!5m2!1sfa!2s"
                    width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen=""></iframe>
            </div>
        </div>
    </div>
    <!-- End .page-content -->
</main>
<!-- End .main -->

<!-- Google Map -->
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDc3LRykbLB-y8MuomRUIY0qH5S6xgBLX4"></script>

{% endblock content %}