blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name="main"),

    path('single_post/', views.single_post, name='single_post'),
    
    #path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('category/<slug:category_slug>/', views.post_list, name='post_list_by_category'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

details/urls.py
from django.urls import path, include
from . import views

app_name = 'details'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_us, name="about_us"),
    #path('contanct/', views.contact_us, name="contact_us"),
    path('contact/', views.feedback, name='contact_us'),
]

ikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls), # admin site
    path('accounts/', include('accounts.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('payment/', include('payment.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('coupons/', include('coupons.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('details.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [

    path('', views.product_list, name='product_list'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/<int:id>/', views.wishlist, name='add_to_wishlist'),
    path('GET/', views.product_list, name='product_list'),
    path('wishlist/remove/<int:id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<str:gender>/', views.product_list, name='product_list_by_gender'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<int:id>/<slug:slug>/<str:color>/', views.product_detail, name='product_detail_by_color'),
]

details/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

class ContactUsMessage(models.Model):
    name = models.CharField(_('نام فرستنده'), max_length=200, help_text="Name of the sender")
    email = models.EmailField(_('ایمیل'), max_length=200)
    phone_number = PhoneNumberField(_('شماره تلفن'), null=True, blank=True)
    subject = models.CharField(_('موضوع پیام'), null=True, blank=True, max_length=200)
    body = models.TextField(_('متن پیام'))
    created_date = models.DateTimeField(_('تاریخ ایجاد'), auto_now_add=True)

    class Meta:
        verbose_name = _('تماس با ما')
        verbose_name_plural = _('تماس با ما')

    def __str__(self):
        return f"{self.name} - {self.email}"

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from multiselectfield import MultiSelectField
from django.conf import settings
from parler.models import TranslatableModel, TranslatedFields
from django.utils.translation import gettext_lazy as _

class BookmarkProduct(models.Model):
    user = models.ForeignKey(User, related_name="user", on_delete=models.DO_NOTHING)
    product = models.ForeignKey('Product', related_name="products", on_delete=models.DO_NOTHING)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "bookmark_product"
        # ordering = ('-created',)
        verbose_name = _('لیست علاقه مندی ها')
        verbose_name_plural = _('لیست علاقه مندی ها')

class Category(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(_('عنوان'), max_length=200, db_index=True),
        slug = models.SlugField(max_length=200, unique=True, db_index=True),
    )

    class Meta:
        # ordering = ('name',)
        verbose_name = _('دسته بندی محصولات')
        verbose_name_plural = _('دسته بندی محصولات')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])

# class ProductQuerySet(TranslatableQuerySet, TreeQuerySet):
#     def as_manager(cls):
#         manager = AvailableProductManager.from_queryset(cls)()
#         manager._built_with_as_manager = True
#         return manager
#     as_manager.queryset_only = True
#     as_manager = classmethod(as_manager)

# class AvailableProductManager(TreeManager, TranslatableManager):
#     _queryset_class = ProductQuerySet
#     def get_querySet(self):
#         return super(AvailableProductManager, self).get_queryset().filter(available=True)
     

class Product(TranslatableModel):

    GENDER_CHOICES = (
        ('men', _('مردانه')),
        ('women', _('زنانه'))
    )

    SEASON_CHOICES = (
        ('spring', _('بهار')),
        ('summer', _('تابستان')),
        ('autumn', _('پاییز')),
        ('winter', _('زمستان')),
    )

    COLOR_CHOICES = (
        ('red', _('قرمز')),
        ('brown', _('قهوه ای')),
        ('yellow', _('زرد')),
        ('black', _('مشکی')),
        ('blue', _('آبی')),
        ('green', _('سبز')),
        ('pink', _('صورتی')),
        ('gray', _('خاکستری')),
    )

    SIZE_CHOICES = (
        ('XS', 'XS'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
    )

    translations = TranslatedFields(
        name = models.CharField(_('عنوان'), max_length=200, db_index=True),
        slug = models.SlugField(max_length=200, db_index=True),
        short_description = RichTextUploadingField(_('توضیحات مختصر'), blank=True, null=True),
        long_description = RichTextUploadingField(_('توضیحات جامع'), blank=True, null=True),
        material = models.CharField(_('نوع جنس'), max_length=50),
    )
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    image = models.ImageField(_('تصویر محصول'), upload_to='products/%Y/%m/%d', blank=True, null=True)
    visit_num = models.PositiveIntegerField(_('تعداد بازدید'), default=0)
    price = models.PositiveIntegerField(_('قیمت'), default=0)
    is_available = models.BooleanField(_('در دسترس'), default=True)
    created = models.DateTimeField(_('تاریخ ایجاد'), auto_now_add=True)
    updated = models.DateTimeField(_('تاریخ بروزرسانی'), auto_now=True)

    size = MultiSelectField(_('سایز'), choices=SIZE_CHOICES)
    gender = models.CharField(_('جنسیت'), max_length=50, choices=GENDER_CHOICES)
    color = MultiSelectField(_('رنگ'), choices=COLOR_CHOICES)
    season = models.CharField(_('فصل'), max_length=50, choices=SEASON_CHOICES)
    #supplier = models.ForeignKet(Supplier, related_name='suppliers', on_delete=models.CASCADE)

    # objects = models.Manager()  # The default manager
    # available = AvailableProductManager()  # Our custom manager

    #quantity = models.IntegerField()

    class Meta:
        # ordering = ('name',)
        # index_together = (('id', 'slug'),)
        verbose_name = _('محصول')
        verbose_name_plural = _('محصولات')

    # @property
    # def calculate_qty(self):
    #     return qty

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])


class CommentManager(models.Manager):
    def all_comments(self):
        qs = super().filter(parent=None)
        return qs

class ProductComments(models.Model):
    product = models.ForeignKey(Product, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField(_('متن پیام'), max_length=1500)
    parent = models.ForeignKey('ProductComments', null=True, blank=True, on_delete=models.CASCADE)
    created = models.DateTimeField(_('تاریخ ایجاد'), auto_now_add=True)
    active = models.BooleanField(default=True)

    objects = CommentManager()

    class Meta:
        ordering = ['-created']
        verbose_name = _("کامنت")
        verbose_name_plural = _("کامنت ها")

    def __str__(self):
        return str(self.user.username)

    def children(self): # replies
        return ProductComments.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True


# class Clothes(product):

#     GENDER_CHOICES = (
#         ('M', 'Male'),
#         ('F', 'Female')
#     )

#     SEASON_CHOICES = (
#         ('Sp', 'Spring'),
#         ('Su', 'Summer'),
#         ('Au', 'Autumn'),
#         ('W', 'Winter')
#     )

#     size = models.IntegerField()
#     gender = models.CharField(max_length=50, choices=GENDER_CHOICES)
#     color = models.CharField(max_length=50)
#     material = models.CharField()
#     season = models.CharField(max_length=50, choices=SEASON_CHOICES)
#     supplier = models.CharField(max_length=200)

#     class Meta:
#         ordering = ('name',)
#         index_together = (('id', 'slug'),)

#     def __str__(self):
#         return self.name

#     def get_absolute_url(self):
#         return reverse("shop:product_detail", args=[self.id, self.slug])

details/forms.py
from django import forms
from .models import ContactUsMessage
from django.forms.widgets import TextInput
from django.utils.translation import gettext_lazy as _

class ContactUsForm(forms.ModelForm):
    name = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('نام *')}))
    email = forms.EmailField(label=False, widget=forms.TextInput(attrs={'placeholder': _('ایمیل *')}))
    phone_number = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('شماره تلفن همراه')}))
    subject = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('موضوع پیام')}))
    body = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': _('متن پیام شما *')}))

    class Meta:
        model = ContactUsMessage
        fields = ('name', 'email', 'phone_number', 'subject', 'body')

details/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from . import forms
from shop.models import Product
from django.contrib.auth.models import User


def home(request):
    latest_products = Product.objects.all()[:10]
    context = {'products': latest_products}
    return render(request, 'details/home.html', context=context)

def about_us(request):
    user = User.objects.all()
    context = {'user': user}
    return render(request, 'details/about.html', context=context)

def feedback(request):
    if request.method == 'POST':
        feedback = forms.ContactUsForm(request.POST)
        if feedback.is_valid():
            feedback.save()
            messages.add_message(request, messages.INFO, 'ممنون از اینکه نظرات خود را با ما در میان میگذارید.')
            return redirect('details:contact_us')
    else:
        feedback = forms.ContactUsForm()
    return render(request, 'details/contact.html', {'feedback': feedback})

shop/views.py
from orders.models import OrderItem
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, BookmarkProduct
from cart.forms import CartAddProductForm
from django.db.models import F
from django.utils.timezone import now, timedelta
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .recommender import Recommender
from .filters import ProductFilter
from django.contrib import auth

def wishlist(request, id=None):
    cart_product_form = CartAddProductForm()
    wishlist_products = list(BookmarkProduct.objects.filter(user=request.user).values('product'))
    products = [Product.objects.get(id=product.get('product')) for product in wishlist_products]
    if id:
        # get User
        user = auth.get_user(request)
        #Trying to get a bookmark from the table, or create a new one
        bookmark, created = BookmarkProduct.objects.get_or_create(user=user, product_id=id)
        # If no new bookmark has been created,
        # Then we believe that the request was to delete the bookmark
        # if not created:
        #     bookmark.delete()

    page = request.GET.get('page', 1)
    paginator = Paginator(products, 5)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/wishlist.html', {'products': products, 'cart_product_form': cart_product_form,})

def remove_from_wishlist(request, id=None):
    print('remove')
    user = auth.get_user(request)
    bookmark = BookmarkProduct.objects.get(user=user, product_id=id)
    print(bookmark)
    bookmark.delete()
    return redirect('shop:wishlist')

def product_list(request, category_slug=None, gender=None):


    language = request.LANGUAGE_CODE
    products = Product.objects.filter(is_available=True)
    number_of_products = len(products)

    gender = None
    if gender:
        products = products.filter(gender=gender) 

    category = None
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, 
                                    translations__slug=category_slug,
                                    translations__language_code=language)
        products = products.filter(category=category)

    # Filtering with django-filters
    filters = ProductFilter(request.GET, queryset=products)

    page = request.GET.get('page', 1)
    paginator = Paginator(filters.qs, 3)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {'category': category, 'categories': categories, 'products': products, 'now': now(),
                'timedelta': timedelta(days=1), 'number_of_products': number_of_products, 
                'template_name': 'shop/star_rate.html', 'filter': filters,}
    return render(request, 'shop/list.html', context=context)

def product_detail(request, id, slug, color=None):

    language = request.LANGUAGE_CODE
    products = Product.objects.filter(is_available=True) # Related products in detail page
    product = get_object_or_404(Product, id=id,
                                translations__language_code=language, 
                                translations__slug=slug,
                                is_available=True)

    is_there_any_order_with_this_product = OrderItem.objects.filter(product=product, order__first_name=request.user.first_name).exists()

    # The code below get next and previous object
    # and if the object does not exist, set it to None.
    try:
        next_product_id = product.id + 1
        next_product = get_object_or_404(Product ,id=next_product_id)
    except:
        next_product = None
    try:
        previouse_product_id = product.id - 1
        previous_product = get_object_or_404(Product ,id=previouse_product_id)
    except:
        previous_product = None

    # Everytime user click on a product add 1 to visit_num using F() object and show in list of product page.
    product.visit_num = F('visit_num') + 1
    product.save()
    cart_product_form = CartAddProductForm()

    # Recommendation System with Redis
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 6)
    print(recommended_products)

    context = {'product': product, 'cart_product_form': cart_product_form, 'now': now(), 'template_name': 'shop/star_rate.html', 'is_there_any_order':is_there_any_order_with_this_product,
                'timedelta': timedelta(days=1), 'products': products, 'next_product': next_product,
                'previous_product': previous_product, 'recommended_products': recommended_products,
                'share_telegram': {'url': product.get_absolute_url, 'text': product.name, 'link_text': "<i title='Telegram' class='fa fa-telegram mr-3' style='font-size:24px;color:#2196F3;'></i>" },
                'share_whatsapp': {'url': product.get_absolute_url, 'text': "<i title='Whatsapp' class='fab fa fa-whatsapp mr-3' style='font-size:24px;color:#1bd741;'></i>" },
                'share_linkedin': {'url': product.get_absolute_url},
                }
    return render(request, 'shop/detail.html', context=context)

shop/templates/shop/pagination.html
{% load i18n %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if products.has_other_pages %} {% with products.number|stringformat:"i" as pgnumber %} {% with myfilter='page='|add:pgnumber|add:'&' request_query=request.META.QUERY_STRING %} {% if products.has_previous %}
        <li class="page-item">
            <a class="page-link page-link-prev" href="?page={{ products.previous_page_number }}&{{ request_query|cut:myfilter }}" aria-label="Previous" tabindex="-1" aria-disabled="true">
                <span aria-hidden="true"><i class="icon-long-arrow-right"></i></span>{% trans "قبلی" %}
            </a>
        </li>
        {% endif %} {% if products.number != 1 %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="?page=1&{{ request_query|cut:myfilter }}">1</a>
        </li>
        {% endif %} {% if products.number != 1 and products.number != 2 and products.number != 3 %}
        <li class="page-item" aria-current="page">
            ...
        </li>
        {% endif %} {% if products.has_previous and products.number != 2 %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="?page={{ products.number|add:-1 }}&{{ request_query|cut:myfilter }}">{{ products.number|add:-1 }}</a>
        </li>
        {% endif %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ products.number}}</a>
        </li>
        {% if products.has_next and products.number != products.paginator.num_pages|add:-1 %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="?page={{ products.number|add:1 }}&{{ request_query|cut:myfilter }}">{{ products.number|add:1 }}</a>
        </li>
        {% endif %} {% if products.number != products.paginator.num_pages and products.number != products.paginator.num_pages|add:-1 and products.number != products.paginator.num_pages|add:-2 %}
        <li class="page-item" aria-current="page">
            ...
        </li>
        {% endif %} {% if products.number != products.paginator.num_pages %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="?page={{ products.paginator.num_pages }}&{{ request_query|cut:myfilter }}">{{ products.paginator.num_pages }}</a>
        </li>
        {% endif %} {% if products.has_next %}
        <li class="page-item">
            <a class="page-link page-link-next" href="?page={{ products.next_page_number }}&{{ request_query|cut:myfilter }}" aria-label="Next">
                        {% trans "بعدی" %}<span aria-hidden="true"><i class="icon-long-arrow-left"></i></span>
            </a>
        </li>
        {% endif %} {% endwith %} {% endwith %} {% endif %}
    </ul>
</nav>

shop/templates/shop/star_rate.html
{% extends "star_ratings/widget_base.html" %} {% load i18n %} 


{% block rating_detail %}
    {% if not user.is_authenticated and not anonymous_ratings and not read_only %}
        <p>{% trans 'Please log in to rate.' %}</p>
    {% endif %}
{% endblock %}

shop/templates/shop/wishlist.html
{% extends "details/base.html" %} {% load i18n static crispy_forms_tags %} {% block meta %}
<meta name="keywords" content="">
<meta name="description" content=""> {% endblock meta %} {% block title %}{% trans "لیست علاقه مندی ها" %}{% endblock title %} {% block content %}
<main class="main">
    <div class="page-header text-center" style="background-image: url('/static/details/assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">{% trans "لیست علاقه مندی" %}<span>{% trans "فروشگاه" %}</span></h1>
        </div>
        <!-- End .container -->
    </div>
    <!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'details:home' %}">خانه{% trans "" %}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'shop:product_list' %}">{% trans "فروشگاه" %}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{% trans "لیست علاقه مندی" %}</li>
            </ol>
        </div>
        <!-- End .container -->
    </nav>
    <!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="container">
            <table class="table table-wishlist table-mobile">
                <thead>
                    <tr>
                        <th>{% trans "محصول" %}</th>
                        <th>{% trans "قیمت" %}</th>
                        <th>{% trans "وضعیت محصول" %}</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    {% for product in products %} 
                    <tr>
                        <td class="product-col">
                            <div class="product">
                                <figure class="product-media">
                                    <a href="{{product.get_absolute_url}}">
                                        <img src="{{product.image.url}}" alt="تصویر محصول">
                                    </a>
                                </figure>

                                <h3 class="product-title">
                                    <a href="{{product.get_absolute_url}}">{{product.name}}</a>
                                </h3>
                                <!-- End .product-title -->
                            </div>
                            <!-- End .product -->
                        </td>
                        <td class="price-col">{{product.price}}</td>
                        {% if product.is_available %}
                        <td class="stock-col"><span class="in-stock">{% trans "موجود" %}</span></td>
                        <td class="action-col">
                            <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                                {% csrf_token %}
                                {{ cart_product_form.quantity }}
                                <input type="submit" value="{% trans 'افزودن به سبد خرید' %}" class="btn btn-block btn-outline-primary-2"></input>
                            </form>
                            <!-- <div class="dropdown">
                                <button class="btn btn-block btn-outline-primary-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="icon-list-alt"></i>انتخاب گزینه ها
                                        </button>

                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">گزینه 1</a>
                                    <a class="dropdown-item" href="#">گزینه 2</a>
                                    <a class="dropdown-item" href="#">گزینه 3</a>
                                </div>
                            </div> -->
                            {% else %}
                                <td class="stock-col"><span class="out-of-stock">{% trans "ناموجود" %}</span></td>
                                <td class="action-col">
                                    <button class="btn btn-block btn-outline-primary-2 disabled">{% trans "ناموجود" %}</button>
                                </td>
                                <td class="remove-col text-left"><button class="btn-remove"><i class="icon-close"></i></button></td>
                            {% endif %}
                        </td>
                        <td class="remove-col text-left"><a href="{% url 'shop:remove_from_wishlist' product.id %}"><button class="btn-remove"><i class="icon-close"></i></button></a></td>
                    </tr>
                    {% endfor %}
                    {% comment %}                      
                    <tr>
                        <td class="product-col">
                            <div class="product">
                                <figure class="product-media">
                                    <a href="#">
                                        <img src="{% static 'details/assets/images/products/table/product-2.jpg' %}" alt="تصویر محصول">
                                    </a>
                                </figure>

                                <h3 class="product-title">
                                    <a href="#">لباس زنانه آبی</a>
                                </h3>
                                <!-- End .product-title -->
                            </div>
                            <!-- End .product -->
                        </td>
                        <td class="price-col">76,000 تومان</td>
                        <td class="stock-col"><span class="in-stock">موجود</span></td>
                        <td class="action-col">
                            <button class="btn btn-block btn-outline-primary-2"><i class="icon-cart-plus"></i>افزودن به سبد خرید</button>
                        </td>
                        <td class="remove-col text-left"><button class="btn-remove"><i
                                            class="icon-close"></i></button></td>
                    </tr>
                    <tr>
                        <td class="product-col">
                            <div class="product">
                                <figure class="product-media">
                                    <a href="#">
                                        <img src="{% static 'details/assets/images/products/table/product-3.jpg' %}" alt="تصویر محصول">
                                    </a>
                                </figure>

                                <h3 class="product-title">
                                    <a href="#">کیف زنانه با بند زنجیری</a>
                                </h3>
                                <!-- End .product-title -->
                            </div>
                            <!-- End .product -->
                        </td>
                        <td class="price-col">52,000 تومان</td>
                        <td class="stock-col"><span class="out-of-stock">ناموجود</span></td>
                        <td class="action-col">
                            <button class="btn btn-block btn-outline-primary-2 disabled">ناموجود</button>
                        </td>
                        <td class="remove-col text-left"><button class="btn-remove"><i
                                            class="icon-close"></i></button></td>
                    </tr>
                    {% endcomment %}
                </tbody>
            </table>
            <!-- End .table table-wishlist -->
            <!-- <div class="wishlist-share">
                <div class="social-icons social-icons-sm mb-2">
                    <label class="social-label">اشتراک گذاری در : </label>
                    <a href="#" class="social-icon" title="فیسبوک" target="_blank"><i
                                    class="icon-facebook-f"></i></a>
                    <a href="#" class="social-icon" title="توییتر" target="_blank"><i
                                    class="icon-twitter"></i></a>
                    <a href="#" class="social-icon" title="اینستاگرام" target="_blank"><i
                                    class="icon-instagram"></i></a>
                    <a href="#" class="social-icon" title="یوتیوب" target="_blank"><i
                                    class="icon-youtube"></i></a>
                    <a href="#" class="social-icon" title="پینترست" target="_blank"><i
                                    class="icon-pinterest"></i></a>
                </div>
            </div> -->
            <!-- End .wishlist-share -->
            {% include "shop/pagination.html" %}
        </div>
        <!-- End .container -->
    </div>
    <!-- End .page-content -->
</main>
<!-- End .main -->
{% endblock content %}